-- Catch-up: bring the legacy production DB onto the Supabase-CLI schema lineage.
--
-- Context. Production (project lhlncsjqxttcdegkqvid) was built by the old custom
-- runner in backend/app/migrations.py, tracked in public.schema_migrations, and
-- stopped at 217_soft_delete_stray_monthly_quota (2026-06-29). The CLI lineage that
-- replaced it (20260615000000_v1_baseline.sql onward) was written for a greenfield
-- project — its own header says "Greenfield: no production data" — so `supabase db
-- push` against prod fails immediately on `create table plans`.
--
-- This migration is the bridge. It is NOT a replay of migrations 0002..20260717;
-- it was generated by diffing the dev project (ycykjisvvrrbgeiirqre, all 42 CLI
-- migrations applied) against prod, so the enum churn (20260622030000 →
-- 20260623000200 → 20260701070739) and the four rounds of cron-SQL fixes collapse
-- into their end state.
--
-- Run order: apply this, then `supabase migration repair --status applied` for every
-- version from 20260615000000 through 20260717000000, after which prod is a normal
-- CLI-managed database and `supabase db push` works.
--
-- DEFERRED — deliberately not in this file (see the report accompanying it):
--   * Partitioning of audit_logs / llm_usage_logs / outbound_call_logs /
--     performance_logs, and the pg_partman extension + partman-maintain cron job.
--     Those four tables hold live rows (667 / 371 / 1980 / 3618); converting a
--     populated table to a partitioned one is a copy-and-swap that wants a
--     maintenance window, not a migration that runs behind a deploy.
--   * public.schema_migrations (the legacy tracker) is left in place as a record of
--     how prod got here. Drop it once this migration is confirmed good.

-- ── 1. Extensions ─────────────────────────────────────────────────────────────
create extension if not exists vector with schema extensions;
create extension if not exists pg_net with schema extensions;   -- keep-warm / anomaly / pricing-sync cron

-- ── 2. Enum types ─────────────────────────────────────────────────────────────
do $$ begin create type billingdocumenttype as enum ('proforma', 'tax_invoice');
exception when duplicate_object then null; end $$;

do $$ begin create type subscriptionstatus as enum ('active', 'lapsed', 'superseded');
exception when duplicate_object then null; end $$;

-- creditorderstatus: prod still has the original ('pending','paid','cancelled').
-- Dev's is ('in_progress','paid','complete','void','on_hold'). Postgres cannot drop
-- enum values, so swap the type. Created complete — unlike the original lineage,
-- which added 'on_hold' via ALTER TYPE ADD VALUE and therefore needed a second
-- transaction before any index could reference it.
do $$
begin
    if not exists (select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid
                   where t.typname = 'creditorderstatus' and e.enumlabel = 'in_progress') then
        create type creditorderstatus_v2 as enum ('in_progress', 'paid', 'complete', 'void', 'on_hold');
        alter table credit_orders alter column status drop default;
        -- Any index whose predicate names an old label pins the column to the old
        -- type. uq_credit_orders_one_pending_per_pack is a legacy-only index (dev
        -- has no equivalent) superseded by uq_credit_orders_one_open_per_tenant.
        drop index if exists uq_credit_orders_one_open_per_tenant;
        drop index if exists uq_credit_orders_one_pending_per_pack;
        alter table credit_orders alter column status type creditorderstatus_v2
            using (case status::text
                when 'pending'   then 'in_progress'
                when 'paid'      then 'paid'
                when 'cancelled' then 'void'
                else 'in_progress'
            end)::creditorderstatus_v2;
        alter table credit_orders alter column status set default 'in_progress';
        drop type creditorderstatus;
        alter type creditorderstatus_v2 rename to creditorderstatus;
    end if;
end $$;

-- ── 3. admin_users: email is the login handle, renamed to username ─────────────
-- Rename, not add+drop: dev has no `email` column, and prod's is NOT NULL, so
-- leaving it would reject every insert the current app code makes.
do $$
begin
    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'admin_users' and column_name = 'email') then
        alter table admin_users rename column email to username;
        alter index if exists uq_admin_user_email_active rename to uq_admin_user_username_active;
    end if;
end $$;

create unique index if not exists uq_admin_user_username_active
    on admin_users (username) where deleted_at is null;

-- pgvector column: 1536 dims (text-embedding-3-small), populated by correction_service.py.
alter table correction_feedback
    add column if not exists value_embedding extensions.vector(1536);

-- ── 4. Align existing columns with the dev reference schema ────────────────────
-- 4a. Missing columns
alter table credit_orders add column if not exists admin_note text;
alter table credit_orders add column if not exists billing_period character varying(10) default 'monthly'::character varying not null;
alter table credit_orders add column if not exists carmen_ar_posted_at timestamp with time zone;
alter table credit_orders add column if not exists carmen_ar_ref character varying(255);
alter table credit_orders add column if not exists expires_at timestamp with time zone;
alter table credit_orders add column if not exists proration_credit_thb numeric(10,2) default 0 not null;
alter table credit_orders add column if not exists rejected_reason text;
alter table credit_orders add column if not exists slip_object_key character varying(512);
alter table credit_orders add column if not exists slip_uploaded_at timestamp with time zone;
alter table credit_packs add column if not exists description text;
alter table credit_packs add column if not exists kind character varying(20) default 'topup'::character varying not null;
alter table llm_usage_logs add column if not exists call_type character varying(16);
alter table outbound_call_logs add column if not exists data_policy character varying(120);
alter table outbound_call_logs add column if not exists provider character varying(60);

-- 4b. Type alignment (json→jsonb, widened numerics)
alter table api_keys alter column scopes type jsonb using scopes::jsonb;
alter table audit_logs alter column after_value type jsonb using after_value::jsonb;
alter table audit_logs alter column before_value type jsonb using before_value::jsonb;
alter table daily_usage_summary alter column total_cost_usd type numeric(14,6) using total_cost_usd::numeric(14,6);
alter table feature_flags alter column enabled_tenants type jsonb using enabled_tenants::jsonb;
alter table monthly_usage_summary alter column total_cost_usd type numeric(14,6) using total_cost_usd::numeric(14,6);
alter table system_configs alter column default_value type jsonb using default_value::jsonb;
alter table system_configs alter column value type jsonb using value::jsonb;
alter table tenant_config_overrides alter column value type jsonb using value::jsonb;

-- 4c. Missing defaults
alter table admin_user_roles alter column tenant_id set default ''::character varying;
alter table admin_users alter column failed_login_attempts set default 0;
alter table admin_users alter column id set default gen_random_uuid();
alter table admin_users alter column is_active set default true;
alter table anomaly_alerts alter column severity set default 'warn'::alertseverity;
alter table ap_invoices alter column id set default gen_random_uuid();
alter table api_key_usage alter column calls set default 0;
alter table api_key_usage alter column cost_usd set default 0;
alter table api_key_usage alter column errors set default 0;
alter table api_key_usage alter column tokens set default 0;
alter table api_keys alter column id set default gen_random_uuid();
alter table api_keys alter column rate_limit_rpm set default 60;
alter table api_keys alter column scopes set default '[]'::jsonb;
alter table banks alter column is_active set default true;
alter table banks alter column sort_order set default 0;
alter table bu_accounting_mapping_entries alter column is_custom set default false;
alter table credit_cards alter column id set default gen_random_uuid();
alter table credit_ledger alter column id set default gen_random_uuid();
alter table credit_orders alter column id set default gen_random_uuid();
alter table credit_orders alter column status set default 'in_progress'::creditorderstatus;
alter table credit_packs alter column is_active set default true;
alter table credit_packs alter column sort_order set default 0;
alter table daily_model_cost alter column call_count set default 0;
alter table daily_model_cost alter column cost_usd set default 0;
alter table daily_model_cost alter column input_tokens set default 0;
alter table daily_model_cost alter column output_tokens set default 0;
alter table daily_usage_summary alter column avg_api_latency_ms set default 0;
alter table daily_usage_summary alter column avg_llm_latency_ms set default 0;
alter table daily_usage_summary alter column p95_api_latency_ms set default 0;
alter table daily_usage_summary alter column total_api_calls set default 0;
alter table daily_usage_summary alter column total_corrections set default 0;
alter table daily_usage_summary alter column total_cost_usd set default 0;
alter table daily_usage_summary alter column total_documents set default 0;
alter table daily_usage_summary alter column total_errors set default 0;
alter table daily_usage_summary alter column total_llm_calls set default 0;
alter table daily_usage_summary alter column total_outbound_calls set default 0;
alter table daily_usage_summary alter column total_submissions set default 0;
alter table daily_usage_summary alter column total_tokens set default 0;
alter table feature_flags alter column enabled_global set default false;
alter table feature_flags alter column rollout_pct set default 0;
alter table job_runs alter column status set default 'running'::jobstatus;
alter table llm_usage_logs alter column completion_tokens set default 0;
alter table llm_usage_logs alter column prompt_tokens set default 0;
alter table llm_usage_logs alter column total_tokens set default 0;
alter table model_pricing alter column input_price_per_1m set default 0;
alter table model_pricing alter column output_price_per_1m set default 0;
alter table model_pricing alter column source set default 'manual'::character varying;
alter table modules alter column is_active set default true;
alter table modules alter column sort_order set default 0;
alter table monthly_usage_summary alter column avg_api_latency_ms set default 0;
alter table monthly_usage_summary alter column avg_llm_latency_ms set default 0;
alter table monthly_usage_summary alter column p95_api_latency_ms set default 0;
alter table monthly_usage_summary alter column total_api_calls set default 0;
alter table monthly_usage_summary alter column total_corrections set default 0;
alter table monthly_usage_summary alter column total_cost_usd set default 0;
alter table monthly_usage_summary alter column total_documents set default 0;
alter table monthly_usage_summary alter column total_errors set default 0;
alter table monthly_usage_summary alter column total_llm_calls set default 0;
alter table monthly_usage_summary alter column total_outbound_calls set default 0;
alter table monthly_usage_summary alter column total_submissions set default 0;
alter table monthly_usage_summary alter column total_tokens set default 0;
alter table ocr_sessions alter column id set default gen_random_uuid();
alter table ocr_sessions alter column is_active set default true;
alter table ocr_tasks alter column id set default gen_random_uuid();
alter table ocr_tasks alter column status set default 'pending'::taskstatus;
alter table plans alter column is_active set default true;
alter table prompt_templates alter column id set default gen_random_uuid();
alter table prompt_templates alter column status set default 'draft'::promptstatus;
alter table quota_usage alter column used set default 0;
alter table quotas alter column id set default gen_random_uuid();
alter table quotas alter column is_custom set default false;
alter table quotas alter column is_hard set default true;
alter table quotas alter column soft_warn_pct set default 0.80;
alter table roles alter column is_system set default false;
alter table system_configs alter column is_secret set default false;
alter table system_configs alter column requires_restart set default false;
alter table tenant_credits alter column balance set default 0;
alter table tenant_credits alter column credits_consumed set default 0;
alter table tenant_credits alter column credits_purchased set default 0;
alter table tenant_modules alter column enabled set default true;
alter table tenants alter column id set default gen_random_uuid();
alter table tenants alter column is_active set default true;
alter table tenants alter column plan set default 'free'::character varying;

-- 4d. NOT NULL tightening — backfill existing NULLs first
update daily_model_cost set call_count = 0 where call_count is null;
alter table daily_model_cost alter column call_count set not null;
update daily_model_cost set cost_usd = 0 where cost_usd is null;
alter table daily_model_cost alter column cost_usd set not null;
update daily_model_cost set input_tokens = 0 where input_tokens is null;
alter table daily_model_cost alter column input_tokens set not null;
update daily_model_cost set output_tokens = 0 where output_tokens is null;
alter table daily_model_cost alter column output_tokens set not null;
update daily_usage_summary set avg_api_latency_ms = 0 where avg_api_latency_ms is null;
alter table daily_usage_summary alter column avg_api_latency_ms set not null;
update daily_usage_summary set avg_llm_latency_ms = 0 where avg_llm_latency_ms is null;
alter table daily_usage_summary alter column avg_llm_latency_ms set not null;
update daily_usage_summary set p95_api_latency_ms = 0 where p95_api_latency_ms is null;
alter table daily_usage_summary alter column p95_api_latency_ms set not null;
update daily_usage_summary set total_api_calls = 0 where total_api_calls is null;
alter table daily_usage_summary alter column total_api_calls set not null;
update daily_usage_summary set total_corrections = 0 where total_corrections is null;
alter table daily_usage_summary alter column total_corrections set not null;
update daily_usage_summary set total_cost_usd = 0 where total_cost_usd is null;
alter table daily_usage_summary alter column total_cost_usd set not null;
update daily_usage_summary set total_documents = 0 where total_documents is null;
alter table daily_usage_summary alter column total_documents set not null;
update daily_usage_summary set total_errors = 0 where total_errors is null;
alter table daily_usage_summary alter column total_errors set not null;
update daily_usage_summary set total_llm_calls = 0 where total_llm_calls is null;
alter table daily_usage_summary alter column total_llm_calls set not null;
update daily_usage_summary set total_outbound_calls = 0 where total_outbound_calls is null;
alter table daily_usage_summary alter column total_outbound_calls set not null;
update daily_usage_summary set total_submissions = 0 where total_submissions is null;
alter table daily_usage_summary alter column total_submissions set not null;
update daily_usage_summary set total_tokens = 0 where total_tokens is null;
alter table daily_usage_summary alter column total_tokens set not null;
update llm_usage_logs set completion_tokens = 0 where completion_tokens is null;
alter table llm_usage_logs alter column completion_tokens set not null;
update llm_usage_logs set prompt_tokens = 0 where prompt_tokens is null;
alter table llm_usage_logs alter column prompt_tokens set not null;
update llm_usage_logs set total_tokens = 0 where total_tokens is null;
alter table llm_usage_logs alter column total_tokens set not null;
update model_pricing set input_price_per_1m = 0 where input_price_per_1m is null;
alter table model_pricing alter column input_price_per_1m set not null;
update model_pricing set output_price_per_1m = 0 where output_price_per_1m is null;
alter table model_pricing alter column output_price_per_1m set not null;
update model_pricing set source = 'manual'::character varying where source is null;
alter table model_pricing alter column source set not null;
update monthly_usage_summary set avg_api_latency_ms = 0 where avg_api_latency_ms is null;
alter table monthly_usage_summary alter column avg_api_latency_ms set not null;
update monthly_usage_summary set avg_llm_latency_ms = 0 where avg_llm_latency_ms is null;
alter table monthly_usage_summary alter column avg_llm_latency_ms set not null;
update monthly_usage_summary set p95_api_latency_ms = 0 where p95_api_latency_ms is null;
alter table monthly_usage_summary alter column p95_api_latency_ms set not null;
update monthly_usage_summary set total_api_calls = 0 where total_api_calls is null;
alter table monthly_usage_summary alter column total_api_calls set not null;
update monthly_usage_summary set total_corrections = 0 where total_corrections is null;
alter table monthly_usage_summary alter column total_corrections set not null;
update monthly_usage_summary set total_cost_usd = 0 where total_cost_usd is null;
alter table monthly_usage_summary alter column total_cost_usd set not null;
update monthly_usage_summary set total_documents = 0 where total_documents is null;
alter table monthly_usage_summary alter column total_documents set not null;
update monthly_usage_summary set total_errors = 0 where total_errors is null;
alter table monthly_usage_summary alter column total_errors set not null;
update monthly_usage_summary set total_llm_calls = 0 where total_llm_calls is null;
alter table monthly_usage_summary alter column total_llm_calls set not null;
update monthly_usage_summary set total_outbound_calls = 0 where total_outbound_calls is null;
alter table monthly_usage_summary alter column total_outbound_calls set not null;
update monthly_usage_summary set total_submissions = 0 where total_submissions is null;
alter table monthly_usage_summary alter column total_submissions set not null;
update monthly_usage_summary set total_tokens = 0 where total_tokens is null;
alter table monthly_usage_summary alter column total_tokens set not null;
update quota_usage set last_updated_at = now() where last_updated_at is null;
alter table quota_usage alter column last_updated_at set not null;

-- ── 5. Tables added after the legacy cutoff ───────────────────────────────────
create table if not exists billing_documents (
    id                 uuid                primary key default gen_random_uuid(),
    tenant_id          uuid                not null references tenants (id),
    order_id           uuid                not null references credit_orders (id),
    doc_type           billingdocumenttype not null,
    number             varchar(50)         not null,
    issue_date         timestamptz         not null,
    seller_name        varchar(255),
    seller_tax_id      varchar(20),
    seller_address     text,
    seller_branch      varchar(100),
    buyer_name         varchar(255),
    buyer_tax_id       varchar(20),
    buyer_address      text,
    buyer_branch       varchar(100),
    buyer_email        varchar(255),
    buyer_contact_name varchar(255),
    buyer_tel          varchar(50),
    pack_code          varchar(20)         not null,
    description        text,
    credits            integer             not null,
    subtotal           numeric(12, 2)      not null,
    vat_rate           numeric(4, 2)       not null default 7.00,
    vat_amount         numeric(12, 2)      not null,
    total              numeric(12, 2)      not null,
    currency           varchar(3)          not null default 'THB',
    created_at         timestamptz         not null default now(),
    updated_at         timestamptz                  default now(),
    deleted_at         timestamptz,
    deleted_by         varchar(100),
    constraint ck_billing_documents_nonneg
        check (subtotal >= 0 and vat_amount >= 0 and total >= 0 and vat_rate >= 0)
);
create index if not exists ix_billing_documents_created_at on billing_documents (created_at);
create index if not exists ix_billing_documents_deleted_at on billing_documents (deleted_at);
create index if not exists ix_billing_documents_tenant_type on billing_documents (tenant_id, doc_type, created_at);
create unique index if not exists uq_billing_documents_number_active on billing_documents (number) where deleted_at is null;

-- period_key is varchar(8): YYYYMMDD (widened from YYYYMM by 20260618110000).
create table if not exists document_sequences (
    scope      varchar(20) not null,
    period_key varchar(8)  not null,
    last_no    integer     not null default 0,
    primary key (scope, period_key)
);

create table if not exists tenant_subscriptions (
    id              uuid               primary key default gen_random_uuid(),
    tenant_id       uuid               not null references tenants (id),
    plan_code       varchar(20)        not null references credit_packs (code),
    doc_allowance   integer            not null,
    docs_used       integer            not null default 0,
    period_start    timestamptz        not null,
    period_end      timestamptz        not null,
    status          subscriptionstatus not null default 'active',
    source_order_id uuid               references credit_orders (id),
    billing_period  varchar(10)        not null default 'monthly',
    cycle_start     timestamptz,
    created_at      timestamptz        not null default now(),
    updated_at      timestamptz                 default now()
);
create index if not exists ix_tenant_subscriptions_tenant on tenant_subscriptions (tenant_id);
create index if not exists ix_tenant_subscriptions_window on tenant_subscriptions (tenant_id, status, period_end);
create unique index if not exists uq_tenant_subscriptions_one_active
    on tenant_subscriptions (tenant_id) where status = 'active';

create table if not exists ar_customer_profiles (
    id             uuid         primary key default gen_random_uuid(),
    buyer_name     varchar(255) not null,
    buyer_tax_id   varchar(20)  not null default '',
    buyer_branch   varchar(100) not null default '',
    carmen_ar_code varchar(50),
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now(),
    deleted_at     timestamptz,
    deleted_by     varchar(100)
);
create unique index if not exists uq_ar_profiles_taxid_branch
    on ar_customer_profiles (buyer_tax_id, buyer_branch)
    where deleted_at is null and buyer_tax_id != '';
create index if not exists ix_ar_profiles_name on ar_customer_profiles (buyer_name) where deleted_at is null;

-- Append-only PDPA evidence: no soft-delete column, no retention purge.
create table if not exists consent_logs (
    id              bigint generated always as identity primary key,
    tenant_id       uuid not null references tenants (id),
    carmen_user_id  varchar(36),
    consent_version varchar(20) not null,
    ip_address      varchar(45),
    user_agent      varchar(400),
    created_at      timestamptz not null default now()
);
create index if not exists ix_consent_logs_tenant_version on consent_logs (tenant_id, consent_version);

create table if not exists user_notifications (
    id         uuid primary key default gen_random_uuid(),
    tenant_id  uuid not null references tenants (id),
    order_id   uuid references credit_orders (id),
    type       varchar(32) not null,
    payload    jsonb not null default '{}',
    read_at    timestamptz,
    created_at timestamptz not null default now()
);
create index if not exists ix_user_notifications_tenant_created
    on user_notifications (tenant_id, created_at desc);

-- ── 6. Indexes missing on pre-existing tables ─────────────────────────────────
create index if not exists ix_anomaly_alerts_open_created ON public.anomaly_alerts USING btree (created_at) WHERE (resolved_at IS NULL);
create index if not exists ix_ap_invoices_carmen_user ON public.ap_invoices USING btree (carmen_user_id);
create index if not exists ix_audit_logs_admin_user ON public.audit_logs USING btree (admin_user_id);
create index if not exists ix_audit_logs_carmen_user ON public.audit_logs USING btree (carmen_user_id);
create index if not exists ix_bug_reports_carmen_user ON public.bug_reports USING btree (carmen_user_id);
create index if not exists ix_correction_feedback_carmen_user ON public.correction_feedback USING btree (carmen_user_id);
create index if not exists ix_correction_feedback_embedding ON public.correction_feedback USING hnsw (value_embedding vector_cosine_ops) WHERE (value_embedding IS NOT NULL);
create index if not exists ix_credit_cards_carmen_user ON public.credit_cards USING btree (carmen_user_id);
create index if not exists ix_daily_usage_summary_date ON public.daily_usage_summary USING btree (summary_date);
create index if not exists ix_llm_usage_logs_carmen_session ON public.llm_usage_logs USING btree (carmen_session_id);
create index if not exists ix_llm_usage_logs_carmen_user ON public.llm_usage_logs USING btree (carmen_user_id);
create index if not exists ix_llm_usage_logs_tenant_created ON public.llm_usage_logs USING btree (tenant_id, created_at);
create index if not exists ix_llm_usage_logs_tenant_module_created ON public.llm_usage_logs USING btree (tenant_id, module_id, created_at);
create index if not exists ix_monthly_usage_summary_date ON public.monthly_usage_summary USING btree (summary_date);
create index if not exists ix_ocr_sessions_carmen_user ON public.ocr_sessions USING btree (carmen_user_id);
create index if not exists ix_ocr_tasks_carmen_user ON public.ocr_tasks USING btree (carmen_user_id);
create index if not exists ix_ocr_tasks_created_module_tenant_active ON public.ocr_tasks USING btree (created_at, module_id, tenant_id) WHERE (deleted_at IS NULL);
create index if not exists ix_outbound_call_logs_tenant_created ON public.outbound_call_logs USING btree (tenant_id, created_at);
create index if not exists ix_performance_logs_carmen_user ON public.performance_logs USING btree (carmen_user_id);
create index if not exists ix_performance_logs_tenant_created ON public.performance_logs USING btree (tenant_id, created_at);
create unique index if not exists uq_ap_invoices_task ON public.ap_invoices USING btree (task_id) WHERE (deleted_at IS NULL);
create unique index if not exists uq_credit_cards_task ON public.credit_cards USING btree (task_id) WHERE (deleted_at IS NULL);
create unique index if not exists uq_credit_orders_one_open_per_tenant ON public.credit_orders USING btree (tenant_id) WHERE ((status = ANY (ARRAY['in_progress'::creditorderstatus, 'on_hold'::creditorderstatus])) AND (deleted_at IS NULL));

-- ── 7. Cron support functions ─────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_build_daily_model_cost(target_date date DEFAULT (((now() AT TIME ZONE 'UTC'::text))::date - 1))
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
    v_day_start  timestamptz := (target_date || 'T00:00:00Z')::timestamptz;
    v_day_end    timestamptz := v_day_start + interval '1 day';
    v_rows       int;
    v_run_id     bigint;
begin
    insert into job_runs (job_name, status, started_at, created_at, updated_at)
    values ('daily-model-cost', 'running'::jobstatus, now(), now(), now())
    returning id into v_run_id;

    insert into daily_model_cost (
        summary_date, tenant_id, module_id, model_name,
        call_count, input_tokens, output_tokens, cost_usd,
        created_at, updated_at
    )
    select
        target_date,
        tenant_id,
        module_id,
        model                               as model_name,
        count(*)                            as call_count,
        coalesce(sum(prompt_tokens),     0) as input_tokens,
        coalesce(sum(completion_tokens), 0) as output_tokens,
        coalesce(sum(cost_usd),          0) as cost_usd,
        now(),
        now()
    from llm_usage_logs
    where created_at >= v_day_start and created_at < v_day_end
      and tenant_id is not null
    group by tenant_id, module_id, model
    on conflict on constraint uq_daily_model_cost do update set
        call_count    = excluded.call_count,
        input_tokens  = excluded.input_tokens,
        output_tokens = excluded.output_tokens,
        cost_usd      = excluded.cost_usd,
        updated_at    = now();

    get diagnostics v_rows = row_count;

    update job_runs
       set status = 'success'::jobstatus, completed_at = now(),
           rows_affected = v_rows, updated_at = now()
     where id = v_run_id;

    return v_rows;

exception when others then
    if v_run_id is not null then
        update job_runs
           set status = 'failed'::jobstatus, completed_at = now(),
               error_message = sqlerrm, updated_at = now()
         where id = v_run_id;
    end if;
    raise;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_build_daily_summary(target_date date DEFAULT (((now() AT TIME ZONE 'UTC'::text))::date - 1))
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
    v_day_start  timestamptz := (target_date || 'T00:00:00Z')::timestamptz;
    v_day_end    timestamptz := v_day_start + interval '1 day';
    v_rows       int;
    v_run_id     bigint;
begin
    insert into job_runs (job_name, status, started_at, created_at, updated_at)
    values ('daily-summary', 'running'::jobstatus, now(), now(), now())
    returning id into v_run_id;

    insert into daily_usage_summary (
        tenant_id, module_id, summary_date,
        total_documents, total_submissions, total_llm_calls,
        total_tokens, total_cost_usd, avg_llm_latency_ms,
        total_api_calls, avg_api_latency_ms, p95_api_latency_ms,
        total_errors, total_corrections, total_outbound_calls,
        created_at, updated_at
    )
    with
    -- Documents uploaded per tenant × module
    docs as (
        select tenant_id::varchar(36) as tenant_id, module_id,
               count(*) as cnt
        from ocr_tasks
        where created_at >= v_day_start and created_at < v_day_end
          and deleted_at is null
        group by 1, 2
    ),
    -- Submissions: credit card + AP invoice (separate queries, then unioned)
    subs as (
        select t.tenant_id::varchar(36) as tenant_id,
               'credit_card_ocr' as module_id, count(*) as cnt
        from credit_cards c
        join ocr_tasks t on t.id = c.task_id
        where c.submitted_at >= v_day_start and c.submitted_at < v_day_end
          and c.deleted_at is null
        group by 1
        union all
        select t.tenant_id::varchar(36) as tenant_id,
               'ap_invoice' as module_id, count(*) as cnt
        from ap_invoices a
        join ocr_tasks t on t.id = a.task_id
        where a.submitted_at >= v_day_start and a.submitted_at < v_day_end
          and a.deleted_at is null
        group by 1
    ),
    -- LLM usage (tenant_id already VARCHAR(36) in log tables)
    llm as (
        select tenant_id, module_id,
               count(*)                       as total_llm_calls,
               coalesce(sum(total_tokens), 0) as total_tokens,
               coalesce(sum(cost_usd),     0) as total_cost_usd,
               coalesce(avg(duration_ms),  0) as avg_llm_latency_ms
        from llm_usage_logs
        where created_at >= v_day_start and created_at < v_day_end
        group by 1, 2
    ),
    -- API performance — tenant-level only (same metrics shared across modules)
    perf as (
        select tenant_id,
               count(*)                                                         as total_api_calls,
               coalesce(avg(duration_ms), 0)                                    as avg_api_latency_ms,
               coalesce(sum(case when status_code >= 500 then 1 else 0 end), 0) as total_errors
        from performance_logs
        where created_at >= v_day_start and created_at < v_day_end
        group by 1
    ),
    -- P95 latency — tenant-level using PERCENT_RANK window function
    p95 as (
        select tenant_id, min(duration_ms) as p95_ms
        from (
            select tenant_id, duration_ms,
                   percent_rank() over (partition by tenant_id order by duration_ms) as pct_rank
            from performance_logs
            where created_at >= v_day_start and created_at < v_day_end
        ) ranked
        where pct_rank >= 0.95
        group by 1
    ),
    -- Corrections (UUID → VARCHAR(36) cast)
    corr as (
        select tenant_id::varchar(36) as tenant_id, count(*) as cnt
        from correction_feedback
        where created_at >= v_day_start and created_at < v_day_end
          and deleted_at is null
        group by 1
    ),
    -- Outbound calls (VARCHAR(36) already)
    outb as (
        select tenant_id, count(*) as cnt
        from outbound_call_logs
        where created_at >= v_day_start and created_at < v_day_end
        group by 1
    ),
    -- Union of all active (tenant, module) pairs — deduplicates automatically
    all_keys as (
        select tenant_id, module_id from docs
        union
        select tenant_id, module_id from llm
    )
    select
        k.tenant_id,
        k.module_id,
        target_date,
        coalesce(d.cnt, 0),
        coalesce(s.cnt, 0),
        coalesce(l.total_llm_calls, 0),
        coalesce(l.total_tokens, 0)::bigint,
        coalesce(l.total_cost_usd, 0),
        coalesce(l.avg_llm_latency_ms, 0),
        coalesce(p.total_api_calls, 0),
        coalesce(p.avg_api_latency_ms, 0),
        coalesce(x.p95_ms, 0),
        coalesce(p.total_errors, 0),
        coalesce(c.cnt, 0),
        coalesce(o.cnt, 0),
        now(),
        now()
    from all_keys k
    left join docs d on d.tenant_id = k.tenant_id and d.module_id = k.module_id
    left join subs s on s.tenant_id = k.tenant_id and s.module_id = k.module_id
    left join llm  l on l.tenant_id = k.tenant_id and l.module_id = k.module_id
    left join perf p on p.tenant_id = k.tenant_id
    left join p95  x on x.tenant_id = k.tenant_id
    left join corr c on c.tenant_id = k.tenant_id
    left join outb o on o.tenant_id = k.tenant_id
    where k.tenant_id is not null
    on conflict on constraint uq_summary_scope_module_date do update set
        total_documents      = excluded.total_documents,
        total_submissions    = excluded.total_submissions,
        total_llm_calls      = excluded.total_llm_calls,
        total_tokens         = excluded.total_tokens,
        total_cost_usd       = excluded.total_cost_usd,
        avg_llm_latency_ms   = excluded.avg_llm_latency_ms,
        total_api_calls      = excluded.total_api_calls,
        avg_api_latency_ms   = excluded.avg_api_latency_ms,
        p95_api_latency_ms   = excluded.p95_api_latency_ms,
        total_errors         = excluded.total_errors,
        total_corrections    = excluded.total_corrections,
        total_outbound_calls = excluded.total_outbound_calls,
        updated_at           = now();

    get diagnostics v_rows = row_count;

    update job_runs
       set status = 'success'::jobstatus, completed_at = now(),
           rows_affected = v_rows, updated_at = now()
     where id = v_run_id;

    return v_rows;

exception when others then
    if v_run_id is not null then
        update job_runs
           set status = 'failed'::jobstatus, completed_at = now(),
               error_message = sqlerrm, updated_at = now()
         where id = v_run_id;
    end if;
    raise;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_build_monthly_summary(target_date date DEFAULT (((now() AT TIME ZONE 'UTC'::text))::date - 1))
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
    v_month_start      date := date_trunc('month', target_date)::date;
    v_next_month_start date := (date_trunc('month', target_date) + interval '1 month')::date;
    v_rows             int;
    v_run_id           bigint;
begin
    insert into job_runs (job_name, status, started_at, created_at, updated_at)
    values ('monthly-summary', 'running'::jobstatus, now(), now(), now())
    returning id into v_run_id;

    insert into monthly_usage_summary (
        tenant_id, module_id, summary_date,
        total_documents, total_submissions, total_llm_calls,
        total_tokens, total_cost_usd, avg_llm_latency_ms,
        total_api_calls, avg_api_latency_ms, p95_api_latency_ms,
        total_errors, total_corrections, total_outbound_calls,
        created_at, updated_at
    )
    select
        tenant_id,
        module_id,
        v_month_start,
        coalesce(sum(total_documents),      0),
        coalesce(sum(total_submissions),    0),
        coalesce(sum(total_llm_calls),      0),
        coalesce(sum(total_tokens),         0)::bigint,
        coalesce(sum(total_cost_usd),       0),
        coalesce(avg(avg_llm_latency_ms),   0),
        coalesce(sum(total_api_calls),      0),
        coalesce(avg(avg_api_latency_ms),   0),
        coalesce(max(p95_api_latency_ms),   0),
        coalesce(sum(total_errors),         0),
        coalesce(sum(total_corrections),    0),
        coalesce(sum(total_outbound_calls), 0),
        now(),
        now()
    from daily_usage_summary
    where summary_date >= v_month_start and summary_date < v_next_month_start
    group by tenant_id, module_id
    on conflict on constraint uq_monthly_summary_scope do update set
        total_documents      = excluded.total_documents,
        total_submissions    = excluded.total_submissions,
        total_llm_calls      = excluded.total_llm_calls,
        total_tokens         = excluded.total_tokens,
        total_cost_usd       = excluded.total_cost_usd,
        avg_llm_latency_ms   = excluded.avg_llm_latency_ms,
        total_api_calls      = excluded.total_api_calls,
        avg_api_latency_ms   = excluded.avg_api_latency_ms,
        p95_api_latency_ms   = excluded.p95_api_latency_ms,
        total_errors         = excluded.total_errors,
        total_corrections    = excluded.total_corrections,
        total_outbound_calls = excluded.total_outbound_calls,
        updated_at           = now();

    get diagnostics v_rows = row_count;

    update job_runs
       set status = 'success'::jobstatus, completed_at = now(),
           rows_affected = v_rows, updated_at = now()
     where id = v_run_id;

    return v_rows;

exception when others then
    if v_run_id is not null then
        update job_runs
           set status = 'failed'::jobstatus, completed_at = now(),
               error_message = sqlerrm, updated_at = now()
         where id = v_run_id;
    end if;
    raise;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_cycle_start(p_start timestamp with time zone, p_now timestamp with time zone)
 RETURNS timestamp with time zone
 LANGUAGE sql
 STABLE
AS $function$

    select p_start + (

        extract(year  from age(p_now, p_start))::int * 12

      + extract(month from age(p_now, p_start))::int

    ) * interval '1 month';

$function$;

CREATE OR REPLACE FUNCTION public.fn_hold_expired_orders()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
declare
    v_rows   int;
    v_run_id bigint;
begin
    insert into job_runs (job_name, status, started_at, created_at, updated_at)
    values ('hold-expired-orders', 'running'::jobstatus, now(), now(), now())
    returning id into v_run_id;

    -- 1. Park expired orders and capture which ones changed.
    with parked as (
        update credit_orders
           set status = 'on_hold', updated_at = now()
         where status = 'in_progress'
           and expires_at is not null and expires_at < now()
           and deleted_at is null
        returning id, tenant_id
    )
    insert into user_notifications (tenant_id, order_id, type, payload, created_at)
    select tenant_id, id, 'on_hold', '{}', now()
    from parked;

    get diagnostics v_rows = row_count;

    -- 2. One-time missing_slip nudge: in_progress, no slip, older than 7 days.
    insert into user_notifications (tenant_id, order_id, type, payload, created_at)
    select o.tenant_id, o.id, 'missing_slip', '{}', now()
    from credit_orders o
    where o.status = 'in_progress'
      and o.slip_object_key is null
      and o.created_at < now() - interval '7 days'
      and o.deleted_at is null
      and not exists (
          select 1 from user_notifications n
           where n.order_id = o.id
             and n.type = 'missing_slip'
      );

    -- 3. 30-day purge.
    delete from user_notifications
     where created_at < now() - interval '30 days';

    update job_runs
       set status = 'success'::jobstatus, completed_at = now(),
           rows_affected = v_rows, updated_at = now()
     where id = v_run_id;

    return v_rows;

exception when others then
    if v_run_id is not null then
        update job_runs
           set status = 'failed'::jobstatus, completed_at = now(),
               error_message = sqlerrm, updated_at = now()
         where id = v_run_id;
    end if;
    raise;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_lapse_expired_subscriptions()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$

declare

    v_rows   int;

    v_run_id bigint;

begin

    insert into job_runs (job_name, status, started_at, created_at, updated_at)

    values ('lapse-subscriptions', 'running'::jobstatus, now(), now(), now())

    returning id into v_run_id;



    update tenant_subscriptions

       set status = 'lapsed', updated_at = now()

     where status = 'active' and period_end <= now();



    get diagnostics v_rows = row_count;



    update job_runs

       set status = 'success'::jobstatus, completed_at = now(),

           rows_affected = v_rows, updated_at = now()

     where id = v_run_id;



    return v_rows;



exception when others then

    if v_run_id is not null then

        update job_runs

           set status = 'failed'::jobstatus, completed_at = now(),

               error_message = sqlerrm, updated_at = now()

         where id = v_run_id;

    end if;

    raise;

end;

$function$;

CREATE OR REPLACE FUNCTION public.fn_purge_inactive_sessions()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$

declare

    v_cutoff      timestamptz := now() - interval '1 hour';

    v_batch       int;

    v_total       int := 0;

    v_run_id      bigint;

begin

    insert into job_runs (job_name, status, started_at, created_at, updated_at)

    values ('session-purge', 'running'::jobstatus, now(), now(), now())

    returning id into v_run_id;



    loop

        delete from ocr_sessions

        where id in (

            select id from ocr_sessions

            where created_at < v_cutoff

            limit 5000

        );

        get diagnostics v_batch = row_count;

        v_total := v_total + v_batch;

        exit when v_batch < 5000;

    end loop;



    update job_runs

       set status = 'success'::jobstatus, completed_at = now(),

           rows_affected = v_total, updated_at = now()

     where id = v_run_id;



    return v_total;



exception when others then

    if v_run_id is not null then

        update job_runs

           set status = 'failed'::jobstatus, completed_at = now(),

               error_message = sqlerrm, updated_at = now()

         where id = v_run_id;

    end if;

    raise;

end;

$function$;

CREATE OR REPLACE FUNCTION public.fn_purge_resolved_alerts()
 RETURNS void
 LANGUAGE sql
AS $function$

    delete from anomaly_alerts

     where resolved_at is not null

       and resolved_at < now() - interval '90 days';

$function$;

-- ── 8. Scheduled jobs ─────────────────────────────────────────────────────────
-- cron.schedule upserts by name, so re-running is safe. partman-maintain is
-- omitted along with the deferred partitioning work.
select cron.schedule('daily-summary',        '17 1 * * *',  $$select fn_build_daily_summary()$$);
select cron.schedule('daily-model-cost',     '22 1 * * *',  $$select fn_build_daily_model_cost()$$);
select cron.schedule('monthly-summary',      '32 1 1 * *',  $$select fn_build_monthly_summary()$$);
select cron.schedule('session-purge',        '0 * * * *',   $$select fn_purge_inactive_sessions()$$);
select cron.schedule('hold-expired-orders',  '7 * * * *',   $$select fn_hold_expired_orders()$$);
select cron.schedule('lapse-subscriptions',  '12 0 * * *',  $$select fn_lapse_expired_subscriptions()$$);
select cron.schedule('anomaly-alerts-purge', '15 3 * * *',  $$select fn_purge_resolved_alerts()$$);

-- These three call back into the app over HTTP. They read the target host from
-- system_configs['app.base_url'] and the bearer from vault 'internal_job_token';
-- both must hold PRODUCTION values or the job silently hits the wrong host.
select cron.schedule('keep-warm', '*/10 * * * *', $$
    select net.http_get(
        url := (select value #>> '{}' from system_configs where key_name = 'app.base_url' limit 1)
               || '/api/v1/health'
    );
$$);

select cron.schedule('anomaly-detection', '40 1 * * *', $$
    select net.http_post(
        url     := (select value #>> '{}' from system_configs where key_name = 'app.base_url' limit 1)
                   || '/api/v1/admin/anomaly/run',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets
                                            where name = 'internal_job_token' limit 1)
        ),
        body    := '{}'::jsonb
    );
$$);

select cron.schedule('pricing-sync', '0 */8 * * *', $$
    select net.http_post(
        url     := (select value #>> '{}' from system_configs where key_name = 'app.base_url' limit 1)
                   || '/api/v1/admin/pricing/sync',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets
                                            where name = 'internal_job_token' limit 1)
        ),
        body    := '{}'::jsonb
    );
$$);

-- The legacy one-shot top-up expiry job is superseded by fn_hold_expired_orders.
select cron.unschedule('expire-topup-571c8cd2')
where exists (select 1 from cron.job where jobname = 'expire-topup-571c8cd2');

-- ── 9. RLS deny-all ───────────────────────────────────────────────────────────
-- No policies anywhere: the app connects as a privileged role that bypasses RLS.
-- This is a backstop in case the Supabase Data API is ever switched on.
do $$
declare t text;
begin
    foreach t in array array[
        'admin_user_roles', 'admin_users', 'anomaly_alerts', 'ap_invoices',
        'ap_vendor_column_mappings', 'ap_vendor_field_mapping_entries', 'api_key_usage', 'api_keys',
        'audit_logs', 'banks', 'billing_documents', 'bu_accounting_configs',
        'bu_accounting_mapping_entries', 'bug_reports', 'correction_feedback', 'credit_cards',
        'credit_ledger', 'credit_orders', 'credit_packs', 'daily_model_cost',
        'daily_usage_summary', 'document_sequences', 'feature_flags', 'job_runs',
        'llm_usage_logs', 'model_pricing', 'modules', 'monthly_usage_summary',
        'ocr_sessions', 'ocr_tasks', 'outbound_call_logs', 'performance_logs',
        'permissions', 'plans', 'prompt_templates', 'quota_usage',
        'quotas', 'role_permissions', 'roles', 'system_configs',
        'tenant_config_overrides', 'tenant_credits', 'tenant_modules', 'tenants'
    ] loop
        execute format('alter table %I enable row level security', t);
    end loop;
end $$;

-- ── 10. Reference data ────────────────────────────────────────────────────────
-- system_configs: 20 rows from dev
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('app.base_url', '"https://carmen-ocr-backend.onrender.com"', 'string', 'system', 'Public HTTPS URL of the FastAPI app — used by pg_net cron jobs (e.g. https://your-app.onrender.com)', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.bank_account_name', '"CARMEN SOFTWARE CO., LTD."', 'string', 'billing', 'Account holder', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.bank_account_no', '"195-4-97445-5"', 'string', 'billing', 'Account number', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.bank_account_type', '"Savings Account (ออมทรัพย์)"', 'string', 'billing', 'Account type', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.bank_branch', '"Ratchada - Sathupradit Intersection"', 'string', 'billing', 'Branch', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.bank_name', '"Bangkok Bank (ธนาคารกรุงเทพ)"', 'string', 'billing', 'Bank name', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.carmen_company_path', '"rptGetCompany/undefined"', 'string', 'billing', 'Optional Carmen API path to fetch buyer company profile', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.cheque_payee', '"CARMEN SOFTWARE CO., LTD."', 'string', 'billing', 'Cheque payee', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.promptpay_id', '"0918592274"', 'string', 'billing', 'PromptPay ID (mobile or tax ID) that customers scan to pay', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_address', '"891/24-25 ถนนพระราม 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพมหานคร 10120"', 'string', 'billing', 'Full address printed on invoices', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_branch', '"สำนักงานใหญ่"', 'string', 'billing', 'Branch name (e.g. สำนักงานใหญ่)', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_name', '"บริษัท คาร์เมน ซอฟต์แวร์ จำกัด"', 'string', 'billing', 'Company name printed on invoices', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_name_en', '"CARMEN SOFTWARE CO., LTD."', 'string', 'billing', 'EN company name', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_phone', '"Tel: 66 2 284 0429 | Fax: 66 2 284 3944"', 'string', 'billing', 'Phone/fax', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.seller_tax_id', '"0105562202751"', 'string', 'billing', '13-digit tax ID printed on invoices', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('billing.vat_rate', '"7"', 'string', 'billing', 'VAT rate % (default 7)', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('maintenance.enabled', 'false', 'bool', 'maintenance', 'Global maintenance mode — blocks all non-admin API access.', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('maintenance.message', '""', 'string', 'maintenance', 'message to user', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('maintenance.window_end', '""', 'string', 'maintenance', 'maintenance end at', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;
insert into system_configs (key_name, value, value_type, category, description, is_secret, requires_restart, default_value, validation_regex) values ('maintenance.window_start', '""', 'string', 'maintenance', 'maintenance start at', false, false, null, null)
    on conflict (key_name) do update set value = excluded.value, value_type = excluded.value_type, category = excluded.category, description = excluded.description, is_secret = excluded.is_secret, requires_restart = excluded.requires_restart, default_value = excluded.default_value, validation_regex = excluded.validation_regex;

-- banks: 8 rows from dev
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('BAY', 'Bank of Ayudhya (Krungsri)', 'ธนาคารกรุงศรีอยุธยา', true, null, 4, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('BBL', 'Bangkok Bank', 'ธนาคารกรุงเทพ', true, null, 1, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('GHL', 'GHL (NTT DATA Payment)', 'จีเอชแอล', true, null, 6, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('KBANK', 'Kasikorn Bank', 'ธนาคารกสิกรไทย', true, null, 2, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('KTC', 'Krungthai Card', 'บริษัท บัตรกรุงไทย จำกัด (มหาชน)', true, null, 5, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('PAYPAL', 'PayPal Thailand', 'เพย์พาล', true, null, 7, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('SCB', 'Siam Commercial Bank', 'ธนาคารไทยพาณิชย์', true, null, 3, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;
insert into banks (code, name, display_name_th, is_active, detection_pattern, sort_order, icon_url, deleted_at, deleted_by) values ('SIAMPAY', 'SiamPay (Asia Pay Thailand)', 'สยามเพย์', true, null, 8, null, null, null)
    on conflict (code) do update set name = excluded.name, display_name_th = excluded.display_name_th, is_active = excluded.is_active, detection_pattern = excluded.detection_pattern, sort_order = excluded.sort_order, icon_url = excluded.icon_url, deleted_at = excluded.deleted_at, deleted_by = excluded.deleted_by;

-- credit_packs: 10 rows from dev
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('p100', 'topup', 100, '290.00', false, 1, null)
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('p1000', 'topup', 1000, '2000.00', false, 3, null)
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('p500', 'topup', 500, '1250.00', false, 2, null)
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('p5000', 'topup', 5000, '7500.00', false, 4, null)
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('pack_large', 'topup', 10000, '20000.00', true, 13, 'Top-up — 10,000 credits')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('pack_medium', 'topup', 2500, '7500.00', true, 12, 'Top-up — 2,500 credits')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('pack_small', 'topup', 500, '2000.00', true, 11, 'Top-up — 500 credits')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('sub_growth', 'subscription', 500, '990.00', true, 2, 'Growth Plan — 500 credits/month')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('sub_pro', 'subscription', 1500, '2490.00', true, 3, 'Professional Plan — 1,500 credits/month')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
insert into credit_packs (code, kind, credits, price_thb, is_active, sort_order, description) values ('sub_starter', 'subscription', 200, '490.00', true, 1, 'Starter Plan — 200 credits/month')
    on conflict (code) do update set kind = excluded.kind, credits = excluded.credits, price_thb = excluded.price_thb, is_active = excluded.is_active, sort_order = excluded.sort_order, description = excluded.description;
